### PR TITLE
Add support for --bytes-as-base64

### PR DESCRIPTION
**Pull request by flokli**
This allows entering bytes as a base64-encoded string, using the standard encoding.

Suggested in https://github.com/ktr0731/evans/discussions/610

### CODE REVIEW

**Comment by flokli** [comment]
I tried extending `fill/proto/interactive_filler_test.go` with an additional field, but I don't understand the test harness enough to understand how to test the filler with other filler opts just for one field. It must work somehow, because we fill bytes passed in there, and read from `./proto.go` file.

@ktr0731, @BenSlabbert, any thoughts?

**Comment by flokli** [comment]
Hmmh, we output bytes as base64, like grpcurl does. It would feel much more natural if this was the default TBH.

**Comment by flokli** [comment]
poke @ktr0731 . WDYT?

**Review by ktr0731 — APPROVED** [review]
Sorry for the delay. The content is very informative, LGTM, thank you!

**Comment by flokli** [comment]
Thanks for the merge! What's your opinion on making base64 input for bytes the default, to be symmetrical with the output? (As in https://github.com/ktr0731/evans/pull/611#issuecomment-1328078890 )

**Comment by ktr0731** [comment]
Oh, I missed that 🙏 
Sounds good. I was worried about backward compatibility, but we can still use the input as is (just like the change in this PR does). Can you give this a shot?

**Comment by ktr0731** [comment]
You can revert your merged changes since I haven't released a new version yet.

**Comment by flokli** [comment]
This is implemented in https://github.com/ktr0731/evans/pull/631, PTAL.

**Pull request merged**
